### ISSUE TITLE
Tutorial for service grid

### ISSUE THREAD

**Issue by keighrim** [lapps/org.lappsgrid.examples#28]
Question: do we need to provide a hands-on tutorial for setting up service grid locally, and/or registering a new service to an existing service grid?

**Comment by ksuderman** [comment]
Yes to both.  However, those should like go on http://wiki.lappsgrid.org rather than here.  Can you edit the wiki?

**Comment by marcverhagen** [comment]
I agree with that, yes to both. There might be usable stuff at http://lapps.github.io/manuals/.

**Comment by keighrim** [comment]
Resolved via http://wiki.lappsgrid.org/installation/ . Closing issue.
