### ISSUE TITLE
Javadoc and groovydoc

### ISSUE THREAD

**Issue by keighrim** [lapps/org.lappsgrid.examples#37]
For instance, the serialization module has both [javadoc](http://lapps.github.io/org.lappsgrid.serialization/apidocs/) and [groovydoc](http://lapps.github.io/org.lappsgrid.serialization/groovydoc/). 
Should we worry about putting them together for later references, or at least an URL-aggregating web page?

**Comment by keighrim** [comment]
Also, `metadata` module seems to be missing its groovydoc 
http://lapps.github.io/org.lappsgrid.metadata/groovydoc/ -> 404 error

@ksuderman I looked at travis log, and the build command is skipping generating javadoc. Is that relevant?

**Comment by ksuderman** [comment]
I think a Maven generated site that links to both Groovy and Java docs is about the best we can do for an aggregating web page.  I have been looking for something that can process both GroovyDoc and JavaDocs and generate a single API reference, but I haven't found anything.  However, the serialization module contains a single Java class (an exception) so the easiest fix might be to simply rewrite it in Groovy.

The documentation is built/deployed in an "after_sucess" script.  If you scroll to the bottom of the travis build log you should see the line

``` bash
$ if [ "$TRAVIS_BRANCH" == "master" ] ; then ./deploy.sh ; fi
```

If you click on the `after_success` link at the end of the line you will get another ~1200 lines of log output!

**Comment by keighrim** [comment]
all fixed
