### ISSUE TITLE
Old versions of pom and all

### ISSUE THREAD

**Issue by ksuderman** [lapps/org.lappsgrid.examples#38]
References to the parent pom and org.lappsgrid.all should be updated to the latest versions:
- [ ] parent-pom:2.0.5
- [ ] org.lappsgrid.all:2.3.1

**Comment by keighrim** [comment]
I was working on this on separate branches of each step. Though I thought 2.3.0 is the latest version of all.

**Comment by ksuderman** [comment]
It was, but I found a few problems. I was just going to announce on the mailing list that I just pushed 2.3.1 to Maven Central.  

If you would like some help finishing the tutorial feel free to assign tasks (new or existing) to @almahmoud (Alex) or @bliu989 (Baian), two of our new programmers.

**Comment by keighrim** [comment]
fixed by #40, #41, #42, #43, #44 .
