### ISSUE TITLE
Various comments on the steps

### ISSUE THREAD

**Issue by marcverhagen** [lapps/org.lappsgrid.examples#49]
Step 1:

- mentions `ANC's Nexus repository`, but this is not mentioned further during step 1 or any later step
- the properties table gives groupID=org.lappsgrid.tutorial, which is different from the pom

Step 4:

- The archive with manifest files has a syntax error in the embedded bean tag (missing closing tag)

 Step 5:

- Error loading WSDL: WSDLException (at /html): faultCode=INVALID_WSDL: Expected element '{http://schemas.xmlsoap.org/wsdl/}definitions'. (Update: tried this with SoapUI 5.3.0 and had no problems)

**Comment by ksuderman** [comment]
Any references to the ANC Nexus repository can be removed.  All Maven artifacts should not be available from Maven Central.

**Comment by keighrim** [comment]
I'll fix them soon.

**Comment by marcverhagen** [comment]
Could you focus on the Step 5 issue, I can fix the others.

**Comment by keighrim** [comment]
Sure. Let me know when you're done. I'll merge the change to all the following steps.

**Comment by keighrim** [comment]
step5 issue should be fixed by #50

**Comment by marcverhagen** [comment]
The XML error in the archive was fixed in https://github.com/lapps/org.lappsgrid.examples/commit/ee6ab76cb064d6ab8a74eacae2e3e384d84d0dd5

**Comment by keighrim** [comment]
All issues resolved. Closing.
